#########################################################
# bucket service
#########################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bucket
spec:
  selector:
    matchLabels:
      app: bucket
  replicas: 1
  template:
    metadata:
      labels:
        app: bucket
    spec:
      containers:
      - name: bucket
        image: andreadelligatti/bucket
        imagePullPolicy: Never
        envFrom:
        - configMapRef:
            name: common-env
        env:
          - name: SERVICES
            value: bucket